import { useEffect, useRef, useState } from "react";
import { APIError, buildKnowledgeIndex, loadKnowledgeIndex } from "./api";
import type { KnowledgeIndexStatus } from "./types";

export type KnowledgeDay = "day-21"|"day-22"|"day-23"|"day-24"|"day-25";

export function KnowledgeNav({active}:{active:number}){return <nav className="knowledge-nav"><a className="knowledge-brand" href="#day-21"><span>KB</span><div><b>Knowledge Studio</b><small>RAG laboratory</small></div></a><div className="knowledge-days">{[21,22,23,24,25].map(day=><a key={day} className={active===day?"active":""} href={`#day-${day}`}>{day}</a>)}</div><a className="knowledge-github" href="https://github.com/eugeneappledev-source/AI-Challenge" target="_blank" rel="noreferrer">Source ↗</a></nav>}

export default function KnowledgeLab({day}:{day:KnowledgeDay}){return <IndexLab day={day}/>}

function IndexLab({day}:{day:KnowledgeDay}){
  const [status,setStatus]=useState<KnowledgeIndexStatus|null>(null);const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);const abortRef=useRef<AbortController|null>(null);
  useEffect(()=>{const controller=new AbortController();loadKnowledgeIndex(controller.signal).then(setStatus).catch(caught=>{if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(toMessage(caught))});return()=>controller.abort()},[]);
  async function rebuild(){if(pending)return;abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setPending(true);setError(null);try{setStatus(await buildKnowledgeIndex(controller.signal))}catch(caught){if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(toMessage(caught))}finally{if(abortRef.current===controller)setPending(false)}}
  return <main className="knowledge-page"><KnowledgeNav active={Number(day.slice(-2))}/><header className="knowledge-hero"><div><p>AI Advent Challenge · День 21</p><h1>Документы<br/><em>становятся знанием</em></h1><span>Две стратегии chunking. Локальные embeddings. Индекс с прозрачными метаданными.</span></div><aside><div><small>КОРПУС</small><strong>{status?.pagesEquivalent||0}</strong><span>эквивалентных страниц</span></div><div><small>ВЕКТОР</small><strong>256D</strong><span>local feature hashing</span></div></aside></header><section className="knowledge-workspace"><div className="knowledge-heading"><div><span>01 / INDEX PIPELINE</span><h2>Собрать локальный индекс</h2><p>README, задания, Go и React-код читаются прямо из репозитория. В индекс попадают source, section и стабильный chunk_id.</p></div><button onClick={()=>void rebuild()} disabled={pending}>{pending?<><i className="knowledge-spinner"/> Индексируем…</>:status?.builtAt?"Пересобрать индекс":"Построить индекс"}</button></div>{error&&<div className="knowledge-error"><b>Индексация не завершена</b><p>{error}</p></div>}{pending&&<div className="index-progress"><i className="knowledge-spinner"/><div><b>scan → chunk × 2 → embed → SQLite</b><p>Обрабатываем документы локально, новые API-ключи не используются.</p></div></div>}
    {status?.builtAt&&<><div className="index-overview"><article><span>BUILT AT</span><b>{new Date(status.builtAt).toLocaleString("ru-RU")}</b></article><article><span>CORPUS</span><b>{status.corpusPath}</b></article><article><span>COVERAGE</span><b>{status.pagesEquivalent}+ pages</b></article></div><div className="knowledge-heading strategy-title"><div><span>02 / COMPARISON</span><h2>Fixed vs Structural</h2><p>Одинаковый корпус превращается в разные наборы чанков — это влияет на границы контекста и retrieval.</p></div></div><div className="strategy-grid">{status.strategies.map(strategy=><article key={strategy.strategy}><header><span>{strategy.strategy==="fixed"?"A":"B"}</span><div><small>STRATEGY</small><h3>{strategy.strategy}</h3></div></header><dl><div><dt>Документы</dt><dd>{strategy.documents}</dd></div><div><dt>Чанки</dt><dd>{strategy.chunks}</dd></div><div><dt>Средний размер</dt><dd>{strategy.averageChars} chars</dd></div><div><dt>Embedding</dt><dd>{strategy.embeddingModel} · {strategy.dimensions}D</dd></div></dl><div className="chunk-samples">{strategy.samples.map(chunk=><details key={chunk.chunkId}><summary><code>{chunk.chunkId}</code><span>{chunk.source}</span></summary><small>{chunk.section}</small><p>{chunk.content}</p></details>)}</div></article>)}</div></>}
    {!status?.builtAt&&!pending&&<div className="knowledge-empty"><b>Индекс ещё не построен</b><p>Нажмите кнопку — обе стратегии будут рассчитаны и сохранены в SQLite.</p></div>}
  </section><footer className="knowledge-footer"><span>Knowledge Studio · Day 21</span><span>Chunking · Embeddings · Metadata · SQLite</span></footer></main>
}
function toMessage(error:unknown){return error instanceof APIError||error instanceof Error?error.message:"Неизвестная ошибка"}
