import { useEffect, useRef, useState } from "react";
import { APIError, buildKnowledgeIndex, compareRAG, loadControlQuestions, loadKnowledgeIndex } from "./api";
import type { ControlQuestion, KnowledgeIndexStatus, RAGComparison } from "./types";

export type KnowledgeDay = "day-21"|"day-22"|"day-23"|"day-24"|"day-25";

export function KnowledgeNav({active}:{active:number}){return <nav className="knowledge-nav"><a className="knowledge-brand" href="#day-21"><span>KB</span><div><b>Knowledge Studio</b><small>RAG laboratory</small></div></a><div className="knowledge-days">{[21,22,23,24,25].map(day=><a key={day} className={active===day?"active":""} href={`#day-${day}`}>{day}</a>)}</div><a className="knowledge-github" href="https://github.com/eugeneappledev-source/AI-Challenge" target="_blank" rel="noreferrer">Source ↗</a></nav>}

export default function KnowledgeLab({day}:{day:KnowledgeDay}){if(day==="day-21")return <IndexLab day={day}/>;return <RAGLab day={day}/>}

function IndexLab({day}:{day:KnowledgeDay}){
  const [status,setStatus]=useState<KnowledgeIndexStatus|null>(null);const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);const abortRef=useRef<AbortController|null>(null);
  useEffect(()=>{const controller=new AbortController();loadKnowledgeIndex(controller.signal).then(setStatus).catch(caught=>{if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(toMessage(caught))});return()=>controller.abort()},[]);
  async function rebuild(){if(pending)return;abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setPending(true);setError(null);try{setStatus(await buildKnowledgeIndex(controller.signal))}catch(caught){if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(toMessage(caught))}finally{if(abortRef.current===controller)setPending(false)}}
  return <main className="knowledge-page"><KnowledgeNav active={Number(day.slice(-2))}/><header className="knowledge-hero"><div><p>AI Advent Challenge · День 21</p><h1>Документы<br/><em>становятся знанием</em></h1><span>Две стратегии chunking. Локальные embeddings. Индекс с прозрачными метаданными.</span></div><aside><div><small>КОРПУС</small><strong>{status?.pagesEquivalent||0}</strong><span>эквивалентных страниц</span></div><div><small>ВЕКТОР</small><strong>256D</strong><span>local feature hashing</span></div></aside></header><section className="knowledge-workspace"><div className="knowledge-heading"><div><span>01 / INDEX PIPELINE</span><h2>Собрать локальный индекс</h2><p>README, задания, Go и React-код читаются прямо из репозитория. В индекс попадают source, section и стабильный chunk_id.</p></div><button onClick={()=>void rebuild()} disabled={pending}>{pending?<><i className="knowledge-spinner"/> Индексируем…</>:status?.builtAt?"Пересобрать индекс":"Построить индекс"}</button></div>{error&&<div className="knowledge-error"><b>Индексация не завершена</b><p>{error}</p></div>}{pending&&<div className="index-progress"><i className="knowledge-spinner"/><div><b>scan → chunk × 2 → embed → SQLite</b><p>Обрабатываем документы локально, новые API-ключи не используются.</p></div></div>}
    {status?.builtAt&&<><div className="index-overview"><article><span>BUILT AT</span><b>{new Date(status.builtAt).toLocaleString("ru-RU")}</b></article><article><span>CORPUS</span><b>{status.corpusPath}</b></article><article><span>COVERAGE</span><b>{status.pagesEquivalent}+ pages</b></article></div><div className="knowledge-heading strategy-title"><div><span>02 / COMPARISON</span><h2>Fixed vs Structural</h2><p>Одинаковый корпус превращается в разные наборы чанков — это влияет на границы контекста и retrieval.</p></div></div><div className="strategy-grid">{status.strategies.map(strategy=><article key={strategy.strategy}><header><span>{strategy.strategy==="fixed"?"A":"B"}</span><div><small>STRATEGY</small><h3>{strategy.strategy}</h3></div></header><dl><div><dt>Документы</dt><dd>{strategy.documents}</dd></div><div><dt>Чанки</dt><dd>{strategy.chunks}</dd></div><div><dt>Средний размер</dt><dd>{strategy.averageChars} chars</dd></div><div><dt>Embedding</dt><dd>{strategy.embeddingModel} · {strategy.dimensions}D</dd></div></dl><div className="chunk-samples">{strategy.samples.map(chunk=><details key={chunk.chunkId}><summary><code>{chunk.chunkId}</code><span>{chunk.source}</span></summary><small>{chunk.section}</small><p>{chunk.content}</p></details>)}</div></article>)}</div></>}
    {!status?.builtAt&&!pending&&<div className="knowledge-empty"><b>Индекс ещё не построен</b><p>Нажмите кнопку — обе стратегии будут рассчитаны и сохранены в SQLite.</p></div>}
  </section><footer className="knowledge-footer"><span>Knowledge Studio · Day 21</span><span>Chunking · Embeddings · Metadata · SQLite</span></footer></main>
}
function toMessage(error:unknown){return error instanceof APIError||error instanceof Error?error.message:"Неизвестная ошибка"}

function RAGLab({day}:{day:KnowledgeDay}){
  const [questions,setQuestions]=useState<ControlQuestion[]>([]);const [question,setQuestion]=useState("Как проект получает HTTPS на VPS?");const [result,setResult]=useState<RAGComparison|null>(null);const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);const abortRef=useRef<AbortController|null>(null);
  useEffect(()=>{const controller=new AbortController();loadControlQuestions(controller.signal).then(items=>{setQuestions(items);if(items[0])setQuestion(items[0].question)}).catch(caught=>{if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(toMessage(caught))});return()=>controller.abort()},[]);
  async function run(){const value=question.trim();if(!value||pending)return;abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setPending(true);setError(null);setResult(null);try{setResult(await compareRAG(value,controller.signal))}catch(caught){if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(toMessage(caught))}finally{if(abortRef.current===controller)setPending(false)}}
  return <main className="knowledge-page"><KnowledgeNav active={Number(day.slice(-2))}/><header className="knowledge-hero rag-hero"><div><p>AI Advent Challenge · День 22</p><h1>Ответ модели<br/><em>получает опору</em></h1><span>Один вопрос, две генерации: без доступа к базе и с контекстом, найденным в локальном индексе.</span></div><aside><div><small>CONTROL SET</small><strong>10</strong><span>проверяемых вопросов</span></div><div><small>RETRIEVAL</small><strong>TOP 5</strong><span>structural chunks</span></div></aside></header><section className="knowledge-workspace"><div className="rag-composer"><span>01 / SAME QUESTION</span><h2>Сравнить ответы</h2><textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Задайте вопрос о проекте…" rows={3}/><div className="control-question-row">{questions.map(item=><button key={item.id} className={question===item.question?"active":""} onClick={()=>setQuestion(item.question)}>{item.id.toUpperCase()}</button>)}</div><button className="rag-run" onClick={()=>void run()} disabled={pending||!question.trim()}>{pending?<><i className="knowledge-spinner"/> Ищем и сравниваем…</>:"Запустить A/B сравнение"}</button></div>{error&&<div className="knowledge-error"><b>Сравнение не завершено</b><p>{error}</p></div>}{pending&&<div className="index-progress"><i className="knowledge-spinner"/><div><b>baseline answer → retrieve top 5 → grounded answer</b><p>Две генерации выполняются на одном вопросе.</p></div></div>}{result&&<><div className="rag-answer-grid"><AnswerCard label="A / БЕЗ RAG" tone="plain" answer={result.withoutRag.answer} model={result.withoutRag.model} duration={result.withoutRag.durationMs} tokens={result.withoutRag.usage.totalTokens}/><AnswerCard label="B / С RAG" tone="grounded" answer={result.withRag.answer} model={result.withRag.model} duration={result.withRag.durationMs} tokens={result.withRag.usage.totalTokens}/></div><div className="knowledge-heading rag-context-title"><div><span>02 / RETRIEVED CONTEXT</span><h2>Что увидела модель</h2><p>Это реальные фрагменты, выбранные локальным cosine similarity до генерации ответа B.</p></div></div><div className="retrieval-list">{result.retrieved.map((item,index)=><details key={item.chunk.chunkId} open={index===0}><summary><b>{String(index+1).padStart(2,"0")}</b><span><strong>{item.chunk.source}</strong><small>{item.chunk.section}</small></span><em>{item.similarityScore.toFixed(3)}</em></summary><p>{item.chunk.content}</p></details>)}</div></>}</section><footer className="knowledge-footer"><span>Knowledge Studio · Day 22</span><span>Question → Retrieve → Context → LLM → Compare</span></footer></main>
}

function AnswerCard({label,tone,answer,model,duration,tokens}:{label:string;tone:string;answer:string;model:string;duration:number;tokens:number}){return <article className={`rag-answer ${tone}`}><header><span>{label}</span><b>{tone==="grounded"?"GROUNDED":"BASELINE"}</b></header><p>{answer}</p><footer><span>{model}</span><span>{duration} ms</span><span>{tokens} tokens</span></footer></article>}
