import { FormEvent, useRef, useState } from "react";
import { APIError, runMCPNetwork } from "./api";
import type { MultiServerResult } from "./types";
import { RadarNav } from "./BusinessResearchLab";

export default function MCPNetworkLab(){
  const [request,setRequest]=useState("");const [budget,setBudget]=useState(200);const [hours,setHours]=useState(8);const [skills,setSkills]=useState("iOS, продуктовая разработка");const [risk,setRisk]=useState("low");
  const [result,setResult]=useState<MultiServerResult|null>(null);const [pending,setPending]=useState(false);const [error,setError]=useState<string|null>(null);const abortRef=useRef<AbortController|null>(null);
  async function submit(event:FormEvent){event.preventDefault();if(!request.trim()||pending)return;abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setPending(true);setResult(null);setError(null);try{setResult(await runMCPNetwork(request.trim(),{budgetUsd:budget,hoursPerWeek:hours,skills:skills.split(",").map(v=>v.trim()).filter(Boolean),riskLevel:risk},controller.signal));}catch(caught){if(!(caught instanceof DOMException&&caught.name==="AbortError"))setError(caught instanceof APIError||caught instanceof Error?caught.message:"Оркестрация не выполнена.");}finally{if(abortRef.current===controller)setPending(false);}}
  return <main className="radar-page network-page"><RadarNav active={20}/>
    <header className="radar-hero network-hero"><div><p className="radar-kicker">AI Advent Challenge · День 20</p><h1>Сеть<br/><em>MCP-серверов</em></h1><p>Один оркестратор читает инструменты двух независимых серверов, маршрутизирует данные между ними и собирает персональный план проверки бизнес-гипотезы.</p><div className="radar-tags"><span>2 MCP servers</span><span>5 tool calls</span><span>Cross-server handoff</span></div></div><aside className="network-map"><div><span>01</span><b>Research MCP</b><small>search · summarize · save</small></div><i>↕ structured handoff</i><div><span>02</span><b>Advisor MCP</b><small>score · action plan</small></div></aside></header>
    <section className="radar-workspace"><div className="radar-heading"><div><span>01 / INPUT</span><h2>Задача и ваши ресурсы</h2></div><p className="research-note">Advisor учитывает реальные ограничения, поэтому результат — гипотеза для проверки, а не обещание дохода.</p></div>
      <form className="network-form" onSubmit={submit}><textarea value={request} onChange={e=>setRequest(e.target.value)} placeholder="Например: найди актуальную небольшую бизнес-идею вокруг AI для мобильных разработчиков…" disabled={pending}/><div className="network-profile"><label><span>Бюджет, USD</span><input type="number" min="0" max="100000" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label><span>Часов в неделю</span><input type="number" min="1" max="80" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><label><span>Навыки через запятую</span><input value={skills} onChange={e=>setSkills(e.target.value)}/></label><label><span>Риск</span><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="low">Низкий</option><option value="medium">Средний</option><option value="high">Высокий</option></select></label></div><footer><button type="button" onClick={()=>setRequest("Найди свежие сигналы вокруг AI-продуктов для малого бизнеса и предложи одну идею, которую можно проверить за неделю.")} disabled={pending}>Подставить сценарий</button><button disabled={!request.trim()||pending}>{pending?<><i className="radar-spinner"/> Серверы работают…</>:"Запустить оркестратор →"}</button></footer></form>
      {error&&<div className="radar-error"><b>Сеть MCP не выполнила задачу</b><p>{error}</p></div>}{pending&&<div className="research-loading"><i className="radar-spinner"/><div><b>Research MCP ⇄ Advisor MCP</b><p>Собираем факты, оцениваем fit, строим план и сохраняем отчёт.</p></div></div>}
      {result&&<section className="network-result"><div className="network-rationale"><span>ORCHESTRATOR DECISION</span><p>{result.rationale}</p><b>{result.servers.length} servers · {result.route.length} calls · {result.usage.totalTokens} tokens</b></div>
        <div className="research-section-heading"><span>02 / DISCOVERY</span><h2>Что нашёл оркестратор</h2><p>Каждый сервер отдаёт свой динамический tools/list.</p></div><div className="network-servers">{result.servers.map((server,index)=><article key={server.name} className={index===0?"research-server":"advisor-server"}><header><b>0{index+1}</b><div><span>MCP SERVER</span><h3>{server.name}</h3></div></header><ul>{server.tools.map(tool=><li key={tool.name}><code>{tool.name}</code><small>{tool.description}</small></li>)}</ul></article>)}</div>
        <div className="research-section-heading"><span>03 / ROUTE</span><h2>Маршрут данных</h2><p>Цвет показывает владельца tool; стрелки — межсерверный handoff.</p></div><div className="network-route">{result.route.map((step,index)=><article key={step.order} className={step.server.startsWith("startup")?"research-step":"advisor-step"}><b>{step.order}</b><div><small>{step.server}</small><h3>{step.tool}</h3><p>{step.inputSummary} <i>→</i> {step.outputSummary}</p></div>{index<result.route.length-1&&<span>→</span>}</article>)}</div>
        <div className="research-section-heading"><span>04 / RANKING</span><h2>Какая гипотеза подходит</h2><p>Fit считается относительно бюджета, времени, навыков и допустимого риска.</p></div><div className="score-grid">{result.scores.items.map((item,index)=><article key={`${item.title}-${index}`}><header><b>{item.fitScore}</b><span>/ 100 FIT</span></header><h3>{item.title}</h3><p>{item.rationale}</p><dl><div><dt>Основание</dt><dd>{item.evidence}</dd></div><div><dt>Усилие</dt><dd>{item.effort}</dd></div><div><dt>Риск</dt><dd>{item.risk}</dd></div></dl></article>)}</div>
        <div className="research-section-heading"><span>05 / ACTION PLAN</span><h2>{result.actionPlan.selectedTitle}</h2><p>{result.actionPlan.goal}</p></div><article className="action-plan"><ol>{result.actionPlan.steps.map((step,index)=><li key={step}><b>0{index+1}</b><span>{step}</span></li>)}</ol><aside><span>BUDGET GUARD</span><p>{result.actionPlan.budgetNote}</p><span>STOP CONDITIONS</span><ul>{result.actionPlan.stopConditions.map(item=><li key={item}>{item}</li>)}</ul><small>Сохранено: {result.savedReport.id}</small></aside></article>
      </section>}
    </section><footer className="radar-footer"><span>Startup & Business Radar</span><span>Research MCP ⇄ Advisor MCP · Orchestrated</span></footer></main>
}
